baseurl: 'https://know72.com'
languageCode: en-us
title: Rule of 72
theme: paperMod
publishDir: docs
googleAnalytics: 
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
paginate: 5
Taxonomies:
  tag: tags
  category: categories
  series: series
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  mainSections:
    - post
  author: Imran Noor Mohamed
  title: Rule of 72
  keyword:
    - Blogs
    - Gists
  images:
    - ''
  DateFormat: 'January 2, 2006'
  defaultTheme: dark
  disableThemeToggle: false
  ShowFullTextinRSS: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  copyright: ashish
  since: '2019'
  highlightjs: true
  highlightjsstyle: github
  UtterancesRepo: ashishtiwari1993/ashish.one
  UtterancesIssueTerm: title
  UtterancesTheme: github-light
  toc: tocbot
  social:
    gravatar: atashish171@gmail.com
    twitter: _ashish_tiwari
    github: ashishtiwari1993
    linkedin: ashish-tiwari-a40a012b
  assets:
    favicon: favicon.png
    favicon16x16: favicon.png
    favicon32x32: favicon.png
    apple_touch_icon: favicon.png
    safari_pinned_tab: favicon.png
  label:
    text: Ashish Tiwari
    iconHeight: 35
  profileMode:
    enabled: false
    imageUrl: 'https://www.gravatar.com/avatar/dcb52889deff3e5017a18de40c57add8?s=200'
  homeInfoParams:
    Title: "Bio  \U0001F44B"
    Content:  >
      ğŸ‘‹ Hi, Iâ€™m Imran


      DE From Germany


      ğŸ§‘â€ğŸ’¼ Technical Product Manager, Delivery Hero


      ğŸ§‘â€ğŸ’» Tech lead, Open source contributor, Marketing Tech lead @Kubernetes


      ğŸ§‘â€ğŸ¤â€ğŸ§‘ Community lover, Speaker, Open source guy


      
  cover:
    linkFullImages: false
    hiddenInList: false
    hiddenInSingle: false
    responsiveImages: true
  editPost:
    URL: 'https://github.com/ashishtiwari1993/ashish.one/tree/master/content'
    Text: Suggest Changes
    appendFilePath: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - name: Categories
      url: /categories/
      weight: -96
    - name: Tags
      url: /tags/
      weight: -95
    - name: Talks
      url: /talks/
      weight: -94
    - name: Search
      url: /search/
      weight: -92
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: -90
